// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PipiApp.Data;

#nullable disable

namespace PipiApp.Data.Migrations
{
    [DbContext(typeof(PipiAppDbContext))]
    [Migration("20230302125430_ToiletsAndPeople")]
    partial class ToiletsAndPeople
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PipiApp.Model.Person", b =>
                {
                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Preference")
                        .HasColumnType("int");

                    b.Property<string>("ToiletRecordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToiletRecordId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PublicId");

                    b.HasIndex("ToiletRecordId");

                    b.HasIndex("ToiletRecordId1");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PipiApp.Model.Toilet", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("OpenHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Toilets")
                        .HasColumnType("int");

                    b.Property<int>("Urinals")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.ToTable("Toilets");
                });

            modelBuilder.Entity("PipiApp.Models.Comment", b =>
                {
                    b.Property<decimal>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CommentId"));

                    b.Property<string>("CommentedToiletId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToiletRecordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CommentId");

                    b.HasIndex("PersonPublicId");

                    b.HasIndex("ToiletRecordId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PipiApp.Model.Person", b =>
                {
                    b.HasOne("PipiApp.Model.Toilet", null)
                        .WithMany("DislikePeople")
                        .HasForeignKey("ToiletRecordId");

                    b.HasOne("PipiApp.Model.Toilet", null)
                        .WithMany("LikePeople")
                        .HasForeignKey("ToiletRecordId1");
                });

            modelBuilder.Entity("PipiApp.Models.Comment", b =>
                {
                    b.HasOne("PipiApp.Model.Person", null)
                        .WithMany("Comments")
                        .HasForeignKey("PersonPublicId");

                    b.HasOne("PipiApp.Model.Toilet", null)
                        .WithMany("Comments")
                        .HasForeignKey("ToiletRecordId");
                });

            modelBuilder.Entity("PipiApp.Model.Person", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PipiApp.Model.Toilet", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DislikePeople");

                    b.Navigation("LikePeople");
                });
#pragma warning restore 612, 618
        }
    }
}
